sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t gustavodm/dockertest -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
