sudo: required
language: generic

services: 
  - docker

before_install:
  -sudo docker build -t gustavodm/dockertest -f Dockerfile.dev .

script:
  -sudo docker run -e CI=true USERNAME/docker-react npm run test 
