version: "3.5"
services:
  web:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.dev
    image: gustavodm/reactweb
    user: "1000:1000"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/home/node/app 
  test:
    image: gustavodm/reactweb
    user: "1000:1000"
    stdin_open: true
    tty: true
    volumes:
      - .:/home/node/app 
    command: ["npm", "run", "test"]