FROM node:15.12.0-alpine3.10

USER node 

RUN mkdir -p /home/node/app 
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install 
COPY --chown=node:node ./ ./

CMD ["npm", "start"]